# Load text and processed text files

In [36]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
from nltk import word_tokenize, FreqDist
from nltk.stem.wordnet import WordNetLemmatizer
import string
import plotly
import plotly.graph_objects as go
import plotly.express as px
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [37]:
file = open('../data/credit_reporting_text.txt')
credit_reporting_text = file.read()
file.close()

file = open('../data/debt_collection_text.txt')
debt_collection_text = file.read()
file.close()

file = open('../data/mortgages_and_loans_text.txt')
mortgages_and_loans_text = file.read()
file.close()

file = open('../data/credit_card_text.txt')
credit_card_text = file.read()
file.close()

file = open('../data/retail_banking_text.txt')
retail_banking_text = file.read()
file.close()

In [38]:
df = pd.read_csv('../data/credit_reporting_text_processed.csv')
credit_reporting_text_processed = df['0'].tolist()

df = pd.read_csv('../data/debt_collection_text_processed.csv')
debt_collection_text_processed = df['0'].tolist()

df = pd.read_csv('../data/mortgages_and_loans_text_processed.csv')
mortgages_and_loans_text_processed = df['0'].tolist()

df = pd.read_csv('../data/credit_card_text_processed.csv')
credit_card_text_processed = df['0'].tolist()

df = pd.read_csv('../data/retail_banking_text_processed.csv')
retail_banking_text_processed = df['0'].tolist()

df = None

# Graph Most Frequent Words

In [39]:
data = FreqDist(credit_reporting_text_processed).most_common(35)
fig = go.Figure()
fig.add_trace(go.Bar(x= [data[i][0] for i in range(len(data))], y=[data[i][1] for i in range(len(data))]))
fig.update_layout(title = "Most Common Words: Credit Reporting")
fig.show()

In [40]:
data = FreqDist(debt_collection_text_processed).most_common(35)
fig = go.Figure()
fig.add_trace(go.Bar(x= [data[i][0] for i in range(len(data))], y=[data[i][1] for i in range(len(data))]))
fig.update_traces(marker_color='moccasin')
fig.update_layout(title = "Most Common Words: Debt Collection")
fig.show()

In [41]:
data = FreqDist(mortgages_and_loans_text_processed).most_common(35)
fig = go.Figure()
fig.add_trace(go.Bar(x= [data[i][0] for i in range(len(data))], y=[data[i][1] for i in range(len(data))]))
fig.update_traces(marker_color='#1f77b4')
fig.update_layout(title = "Most Common Words: Mortgages and Loans")
fig.show()

In [42]:
data = FreqDist(credit_card_text_processed).most_common(35)
fig = go.Figure()
fig.add_trace(go.Bar(x= [data[i][0] for i in range(len(data))], y=[data[i][1] for i in range(len(data))]))
fig.update_traces(marker_color='yellowgreen')
fig.update_layout(title = "Most Common Words: Credit Card")
fig.show()

In [43]:
data = FreqDist(retail_banking_text_processed).most_common(35)
fig = go.Figure()
fig.add_trace(go.Bar(x= [data[i][0] for i in range(len(data))], y=[data[i][1] for i in range(len(data))]))
fig.update_traces(marker_color='darkred')
fig.update_layout(title = "Most Common Words: Retail Banking")
fig.show()

# TF-IDF

## Trying out TF-IDF

In [44]:
# function to concat processed text as a single string inside a list
def concat_words(list):
    # remove any NaN's
    list = [i for i in list if i is not np.nan]

    # concat words
    concat_words = ''
    for word in list:
        concat_words += word + ' '
    return [concat_words]

### Trying out retail banking text

In [45]:
retail_banking_corpus = concat_words(retail_banking_text_processed)

In [46]:
vectorizer = TfidfVectorizer()
X_retail_banking = vectorizer.fit_transform(retail_banking_corpus)

In [47]:
X_retail_banking.shape

(1, 23214)

In [48]:
feature_names = vectorizer.get_feature_names()

AttributeError: 'TfidfVectorizer' object has no attribute 'get_feature_names'

In [ ]:
X_retail_banking_dense = X_retail_banking.T.todense()

In [ ]:
X_retail_banking_dense.shape

(21177, 1)

In [ ]:
df = pd.DataFrame(X_retail_banking_dense, index=feature_names, columns=["score"])
df = df.sort_values(by="score", ascending=False)
df.iloc[0:30]

                score
account      0.580590
bank         0.354186
money        0.224680
would        0.150739
told         0.139046
funds        0.121563
back         0.111722
check        0.111334
called       0.111090
received     0.104467
card         0.102657
said         0.093305
get          0.089053
days         0.086309
sent         0.084082
time         0.083695
one          0.082086
paypal       0.080462
checking     0.078925
call         0.078652
could        0.078279
number       0.077374
chase        0.073136
never        0.071268
information  0.071038
phone        0.070923
email        0.070334
transaction  0.069573
also         0.066772
transfer     0.065694

In [ ]:
FreqDist(retail_banking_text_processed).most_common(30)

[('account', 40415),
 ('bank', 24655),
 ('money', 15640),
 ('would', 10493),
 ('told', 9679),
 ('funds', 8462),
 ('back', 7777),
 ('check', 7750),
 ('called', 7733),
 ('received', 7272),
 ('card', 7146),
 ('said', 6495),
 ('get', 6199),
 ('days', 6008),
 ('sent', 5853),
 ('time', 5826),
 ('one', 5714),
 ('paypal', 5601),
 ('checking', 5494),
 ('call', 5475),
 ('could', 5449),
 ('number', 5386),
 ('chase', 5091),
 ('never', 4961),
 ('information', 4945),
 ('phone', 4937),
 ('email', 4896),
 ('transaction', 4843),
 ('also', 4648),
 ('transfer', 4573)]

It's exactly the same as my FreqDist. I guess I need to use it on multiple corpus.

### Combining retail banking and credit card texts

In [ ]:
credit_card_corpus = concat_words(credit_card_text_processed)

In [ ]:
combined_corpus = credit_card_corpus + retail_banking_corpus

In [ ]:
X_combined = vectorizer.fit_transform(combined_corpus)

In [ ]:
feature_names = vectorizer.get_feature_names()

In [ ]:
X_combined_dense = X_combined.T.todense()

In [ ]:
X_combined_dense.shape

(30162, 2)

In [ ]:
df = pd.DataFrame(X_combined_dense, index=feature_names, columns=["credit_card", "retail"])
df = df.sort_values(by="retail", ascending=False)
df.iloc[0:30]

             credit_card    retail
account         0.313607  0.580524
bank            0.164653  0.354146
money           0.066288  0.224654
would           0.160445  0.150722
told            0.124567  0.139030
funds           0.023437  0.121549
back            0.097007  0.111709
check           0.033841  0.111322
called          0.123258  0.111077
received        0.125591  0.104455
card            0.421574  0.102646
said            0.087504  0.093295
get             0.085332  0.089043
days            0.068399  0.086299
sent            0.066523  0.084073
time            0.108732  0.083685
one             0.136736  0.082076
paypal          0.014502  0.080453
checking        0.015020  0.078916
call            0.085455  0.078643
could           0.077149  0.078270
number          0.067658  0.077365
chase           0.068942  0.073127
never           0.099821  0.071260
information     0.070657  0.071030
phone           0.067843  0.070915
email           0.056032  0.070326
transaction     0.034730  0.069565
also            0.064314  0.066764
transfer        0.021623  0.065687

In [ ]:
df = df.sort_values(by="credit_card", ascending=False)
df.iloc[0:30]

             credit_card    retail
card            0.421574  0.102646
credit          0.400618  0.064365
account         0.313607  0.580524
bank            0.164653  0.354146
would           0.160445  0.150722
payment         0.153163  0.049843
one             0.136736  0.082076
received        0.125591  0.104455
told            0.124567  0.139030
called          0.123258  0.111077
time            0.108732  0.083685
never           0.099821  0.071260
balance         0.098155  0.042704
back            0.097007  0.111709
due             0.091268  0.043250
made            0.090059  0.065328
dispute         0.088627  0.039731
said            0.087504  0.093295
charge          0.086862  0.026329
call            0.085455  0.078643
get             0.085332  0.089043
charges         0.082530  0.028024
late            0.080728  0.008144
company         0.080049  0.043150
could           0.077149  0.078270
pay             0.074792  0.045936
customer        0.073150  0.062670
interest        0.072274  0.010069
information     0.070657  0.071030
closed          0.069324  0.064610

## Running TF-IDF on all text

### Make full corpus

In [ ]:
# already did retail_banking and credit_card
credit_reporting_corpus = concat_words(credit_reporting_text_processed)
debt_collection_corpus = concat_words(debt_collection_text_processed)
mortgages_and_loans_corpus = concat_words(mortgages_and_loans_text_processed)

In [ ]:
full_corpus = (credit_reporting_corpus + debt_collection_corpus + mortgages_and_loans_corpus + 
               credit_card_corpus + retail_banking_corpus)

### Create TF-IDF Matrix

In [ ]:
vectorizer = TfidfVectorizer()
X_full_corpus = vectorizer.fit_transform(full_corpus)
feature_names = vectorizer.get_feature_names()
X_full_corpus_dense = X_full_corpus.T.todense()

In [ ]:
X_full_corpus_dense.shape

(57592, 5)

#### Create dataframe

In [ ]:
column_names = ["credit_reporting", "debt_collection", "mortgages_and_loans", 
                "credit_card", "retail_banking"]

In [ ]:
df = pd.DataFrame(X_full_corpus_dense, index=feature_names, columns=column_names)
df = df.sort_values(by="credit_reporting", ascending=False)
df.iloc[0:15]

,credit_reporting,debt_collection,mortgages_and_loans,credit_card,retail_banking
credit,0.574145,0.407446,0.150777,0.400592,0.064352
report,0.316577,0.170633,0.040935,0.052005,0.026080
account,0.292746,0.308339,0.170611,0.313587,0.580400
information,0.273984,0.168434,0.085929,0.070653,0.071015
reporting,0.205396,0.105084,0.022270,0.018524,0.004150
accounts,0.180527,0.049354,0.011947,0.033494,0.062241
consumer,0.118493,0.067611,0.019921,0.018524,0.013988
dispute,0.089750,0.053531,0.008632,0.088621,0.039723
identity,0.085916,0.050259,0.003006,0.014760,0.012939
please,0.081583,0.069295,0.036720,0.033679,0.033116
remove,0.075733,0.035021,0.011551,0.012045,0.005515
days,0.075630,0.043934,0.073141,0.068394,0.086281
also,0.073331,0.083848,0.077239,0.064309,0.066750
sent,0.072819,0.101401,0.096175,0.066518,0.084055
payment,0.071913,0.085869,0.288118,0.153153,0.049833

In [ ]:
df = df.sort_values(by="debt_collection", ascending=False)

In [ ]:
df = df.sort_values(by="mortgages_and_loans", ascending=False)
df.iloc[0:15]

,credit_reporting,debt_collection,mortgages_and_loans,credit_card,retail_banking
loan,0.046565,0.048817,0.373254,0.007837,0.015452
payment,0.071913,0.085869,0.288118,0.153153,0.049833
mortgage,0.018507,0.015774,0.250498,0.005010,0.005917
would,0.057737,0.101969,0.218331,0.160434,0.150690
account,0.292746,0.308339,0.170611,0.313587,0.580400
payments,0.044822,0.039336,0.166947,0.065877,0.018698
told,0.034536,0.081912,0.151115,0.124559,0.139000
credit,0.574145,0.407446,0.150777,0.400592,0.064352
received,0.071282,0.123384,0.138027,0.125583,0.104433
company,0.061969,0.179820,0.127743,0.080044,0.043140
time,0.053833,0.073641,0.124399,0.108725,0.083667
called,0.028934,0.085174,0.118966,0.123250,0.111054
due,0.053357,0.057183,0.115719,0.091262,0.043241
bank,0.024771,0.038620,0.110151,0.164642,0.354071
pay,0.020780,0.078661,0.107416,0.074787,0.045927

### Create TF-IDF with bigrams

In [ ]:
vectorizer = TfidfVectorizer(ngram_range=(1,2))
X_full_corpus = vectorizer.fit_transform(full_corpus)
feature_names = vectorizer.get_feature_names()
X_full_corpus_dense = X_full_corpus.T.todense()

In [ ]:
df = pd.DataFrame(X_full_corpus_dense, index=feature_names, columns=column_names)
df = df.sort_values(by="credit_reporting", ascending=False)
df.iloc[0:15]

,credit_reporting,debt_collection,mortgages_and_loans,credit_card,retail_banking
credit,0.553215,0.398852,0.149321,0.391922,0.063585
report,0.305036,0.167034,0.040539,0.050880,0.025769
account,0.282074,0.301835,0.168964,0.306800,0.573488
information,0.263996,0.164881,0.085099,0.069124,0.070169
reporting,0.197908,0.102868,0.022055,0.018123,0.004101
accounts,0.173946,0.048313,0.011832,0.032769,0.061499
credit report,0.171306,0.100684,0.021921,0.024305,0.001518
consumer,0.114174,0.066185,0.019729,0.018123,0.013821
dispute,0.086478,0.052402,0.008548,0.086703,0.039249
identity,0.082784,0.049199,0.002977,0.014441,0.012785
please,0.078609,0.067833,0.036366,0.032950,0.032722
remove,0.072973,0.034282,0.011439,0.011784,0.005449
days,0.072873,0.043008,0.072435,0.066914,0.085253
also,0.070658,0.082080,0.076494,0.062918,0.065955
sent,0.070164,0.099262,0.095246,0.065079,0.083054

In [ ]:
df = df.sort_values(by="mortgages_and_loans", ascending=False)
df.iloc[0:15]

,credit_reporting,debt_collection,mortgages_and_loans,credit_card,retail_banking
loan,0.044868,0.047787,0.369651,0.007667,0.015268
payment,0.069291,0.084058,0.285337,0.149838,0.049239
mortgage,0.017832,0.015442,0.248081,0.004902,0.005846
would,0.055632,0.099819,0.216223,0.156962,0.148895
account,0.282074,0.301835,0.168964,0.306800,0.573488
payments,0.043188,0.038506,0.165336,0.064451,0.018475
told,0.033277,0.080185,0.149656,0.121863,0.137345
credit,0.553215,0.398852,0.149321,0.391922,0.063585
received,0.068683,0.120782,0.136695,0.122865,0.103189
company,0.059710,0.176027,0.126510,0.078312,0.042627
time,0.051871,0.072088,0.123198,0.106372,0.082671
called,0.027879,0.083378,0.117818,0.120583,0.109731
due,0.051412,0.055977,0.114602,0.089287,0.042726
bank,0.023868,0.037805,0.109088,0.161079,0.349854
pay,0.020023,0.077001,0.106379,0.073168,0.045380

# CountVectorizer

In [ ]:
# using bigram
cv = CountVectorizer(ngram_range=[1,2])
X_cv_bigram = cv.fit_transform(full_corpus)
feature_names = cv.get_feature_names()
X_cv_bigram_dense = X_cv_bigram.T.todense()

In [ ]:
df = pd.DataFrame(X_cv_bigram_dense, index=feature_names, columns=column_names)
df = df.sort_values(by="credit_reporting", ascending=False)
df.iloc[0:15]

,credit_reporting,debt_collection,mortgages_and_loans,credit_card,retail_banking
credit,222999,38719,15599,32460,4481
report,122959,16215,4235,4214,1816
account,113703,29301,17651,25410,40415
information,106416,16006,8890,5725,4945
reporting,79776,9986,2304,1501,289
accounts,70117,4690,1236,2714,4334
credit report,69053,9774,2290,2013,107
consumer,46023,6425,2061,1501,974
dispute,34859,5087,893,7181,2766
identity,33370,4776,311,1196,901
please,31687,6585,3799,2729,2306
remove,29415,3328,1195,976,384
days,29375,4175,7567,5542,6008
also,28482,7968,7991,5211,4648
sent,28283,9636,9950,5390,5853

In [ ]:
df = df.sort_values(by="debt_collection", ascending=False)
df.iloc[0:15]

,credit_reporting,debt_collection,mortgages_and_loans,credit_card,retail_banking
debt,25767,40246,2192,1120,386
credit,222999,38719,15599,32460,4481
account,113703,29301,17651,25410,40415
collection,26290,17936,852,357,104
company,24069,17088,13216,6486,3004
report,122959,16215,4235,4214,1816
information,106416,16006,8890,5725,4945
received,27686,11725,14280,10176,7272
letter,25513,10413,7936,5577,2705
never,26385,10049,8811,8088,4961
reporting,79776,9986,2304,1501,289
credit report,69053,9774,2290,2013,107
would,22425,9690,22588,13000,10493
sent,28283,9636,9950,5390,5853
payment,27931,8160,29808,12410,3470

# Lemmatize corpora

I notice that the vectors have a lot of words like "payment"/"payments" and "account"/"accounts" repeated as top words.

**Note**: Here I'm using the dataframe from CountVectorization. I think using the TF-IDF dataframe would be comparable for EDA purposes, if not exactly the same.

## Examine most frequent words from all classes

In [ ]:
# Create combined list of top words

top_words = []
for i in range(5):
    
    # sort df by column position
    df = df.sort_values(by=df.columns[i], ascending=False)
    
    # make a list out of the top 100 index values
    top_100 = df[df.columns[i]].index.values.tolist()[0:100]
    top_words += top_100

In [ ]:
# look at the top words with duplicates removed 
top_words_set = set(top_words)
print(len(top_words_set))
top_words_set

228

{'able',
 'access',
 'account',
 'accounts',
 'accurate',
 'act',
 'address',
 'agencies',
 'agency',
 'alleged',
 'also',
 'america',
 'amount',
 'another',
 'app',
 'application',
 'applied',
 'asked',
 'back',
 'balance',
 'bank',
 'bank account',
 'bank america',
 'bill',
 'block',
 'branch',
 'bureaus',
 'business',
 'call',
 'called',
 'calls',
 'capital',
 'capital one',
 'car',
 'card',
 'cards',
 'case',
 'cash',
 'charge',
 'charged',
 'charges',
 'chase',
 'check',
 'checking',
 'checking account',
 'citi',
 'citibank',
 'claim',
 'closed',
 'closing',
 'collect',
 'collection',
 'collection agency',
 'collections',
 'company',
 'complaint',
 'consumer',
 'contact',
 'contacted',
 'contract',
 'copy',
 'could',
 'credit',
 'credit bureaus',
 'credit card',
 'credit report',
 'credit reporting',
 'creditor',
 'customer',
 'customer service',
 'date',
 'day',
 'days',
 'debit',
 'debt',
 'deleted',
 'department',
 'deposit',
 'deposited',
 'dispute',
 'disputed',
 'documents',
 'due',
 'email',
 'equifax',
 'escrow',
 'even',
 'experian',
 'fair',
 'fair credit',
 'fargo',
 'fcra',
 'fee',
 'fees',
 'file',
 'filed',
 'financial',
 'first',
 'following',
 'forbearance',
 'fraud',
 'fraudulent',
 'full',
 'funds',
 'get',
 'going',
 'got',
 'help',
 'hold',
 'home',
 'identity',
 'identity theft',
 'immediately',
 'inaccurate',
 'information',
 'inquiries',
 'inquiry',
 'insurance',
 'interest',
 'investigation',
 'issue',
 'items',
 'know',
 'late',
 'law',
 'legal',
 'lender',
 'letter',
 'letters',
 'like',
 'limit',
 'listed',
 'loan',
 'loans',
 'made',
 'mail',
 'make',
 'may',
 'merchant',
 'mine',
 'money',
 'month',
 'monthly',
 'months',
 'mortgage',
 'must',
 'name',
 'need',
 'never',
 'new',
 'notice',
 'number',
 'one',
 'online',
 'open',
 'opened',
 'original',
 'owe',
 'owed',
 'paid',
 'pay',
 'payment',
 'payments',
 'paypal',
 'person',
 'phone',
 'please',
 'process',
 'proof',
 'property',
 'provide',
 'provided',
 'purchase',
 'rate',
 'receive',
 'received',
 'refinance',
 'refund',
 'remove',
 'removed',
 'report',
 'reported',
 'reporting',
 'reports',
 'representative',
 'request',
 'requested',
 'response',
 'said',
 'score',
 'section',
 'see',
 'send',
 'sent',
 'service',
 'services',
 'several',
 'since',
 'spoke',
 'state',
 'stated',
 'statement',
 'still',
 'take',
 'theft',
 'time',
 'times',
 'told',
 'transaction',
 'transactions',
 'transfer',
 'transunion',
 'tried',
 'two',
 'us',
 'use',
 'used',
 'validation',
 'verified',
 'violation',
 'want',
 'wells',
 'wells fargo',
 'went',
 'within',
 'without',
 'would',
 'years'}

## Perform lemmatization

In [ ]:
lemm = WordNetLemmatizer()

In [ ]:
def make_lemma(list_of_words):
    # remove any NaN's
    list_of_words = [i for i in list_of_words if i is not np.nan]
    
    list_to_return = []
    for idx, word in enumerate(list_of_words):
        list_to_return.append(lemm.lemmatize(word))
    return list_to_return

In [ ]:
credit_reporting_lemmatized = make_lemma(credit_reporting_text_processed)

In [ ]:
debt_collection_lemmatized = make_lemma(debt_collection_text_processed)
mortgages_and_loans_lemmatized = make_lemma(mortgages_and_loans_text_processed)
credit_card_lemmatized = make_lemma(credit_card_text_processed)
retail_banking_lemmatized = make_lemma(retail_banking_text_processed)

In [ ]:
# create a lemmatized full corpus

# full_corpus_lemmatized = ([credit_reporting_lemmatized] + [debt_collection_lemmatized] + 
#                           [mortgages_and_loans_lemmatized] + [credit_card_lemmatized] + 
#                           [retail_banking_lemmatized])

I don't have `full_corpus_lemmatized` in the correct structure for TF-IDF. It needs to be a list of five items, and each item is a single string with spaces between the words.

In [ ]:
credit_reporting_lemmatized = concat_words(credit_reporting_lemmatized)
debt_collection_lemmatized = concat_words(debt_collection_lemmatized)
mortgages_and_loans_lemmatized = concat_words(mortgages_and_loans_lemmatized)
credit_card_lemmatized = concat_words(credit_card_lemmatized)
retail_banking_lemmatized = concat_words(retail_banking_lemmatized)

In [ ]:
# re-create another lemmatized full corpus
full_corpus_lemmatized = (credit_reporting_lemmatized + debt_collection_lemmatized + 
                          mortgages_and_loans_lemmatized + credit_card_lemmatized + 
                          retail_banking_lemmatized)

# TF-IDF on lemmatized corpus

In [ ]:
vectorizer = TfidfVectorizer(ngram_range=(1,2))
X_lemmatized_corpus = vectorizer.fit_transform(full_corpus_lemmatized)
feature_names = vectorizer.get_feature_names()
X_lemmatized_corpus_dense = X_lemmatized_corpus.T.todense()

In [ ]:
df = pd.DataFrame(X_lemmatized_corpus_dense, index=feature_names, columns=column_names)
df = df.sort_values(by="credit_reporting", ascending=False)
df.iloc[0:5]

,credit_reporting,debt_collection,mortgages_and_loans,credit_card,retail_banking
credit,0.505595,0.372459,0.136271,0.370545,0.061344
account,0.416318,0.325808,0.163319,0.314431,0.590591
report,0.314272,0.188310,0.042440,0.052804,0.025841
information,0.241099,0.153487,0.076908,0.064074,0.065382
reporting,0.180959,0.095794,0.019932,0.016837,0.003814

In [ ]:
df = df.sort_values(by="debt_collection", ascending=False)
df.iloc[0:5]

,credit_reporting,debt_collection,mortgages_and_loans,credit_card,retail_banking
debt,0.062932,0.401310,0.020148,0.013360,0.005609
credit,0.505595,0.372459,0.136271,0.370545,0.061344
account,0.416318,0.325808,0.163319,0.314431,0.590591
collection,0.069118,0.210940,0.011423,0.007368,0.002811
report,0.314272,0.188310,0.042440,0.052804,0.025841

In [ ]:
df = df.sort_values(by="mortgages_and_loans", ascending=False)
df.iloc[0:5]

,credit_reporting,debt_collection,mortgages_and_loans,credit_card,retail_banking
payment,0.102687,0.114044,0.407109,0.198426,0.062980
loan,0.052763,0.053706,0.379274,0.008251,0.015956
mortgage,0.016655,0.015355,0.228727,0.004819,0.005530
would,0.050788,0.092880,0.195322,0.145342,0.138485
account,0.416318,0.325808,0.163319,0.314431,0.590591

In [ ]:
df = df.sort_values(by="credit_card", ascending=False)
df.iloc[0:5]

,credit_reporting,debt_collection,mortgages_and_loans,credit_card,retail_banking
card,0.041806,0.043862,0.010619,0.419525,0.104593
credit,0.505595,0.372459,0.136271,0.370545,0.061344
account,0.416318,0.325808,0.163319,0.314431,0.590591
payment,0.102687,0.114044,0.407109,0.198426,0.062980
bank,0.024043,0.039606,0.103524,0.155371,0.340056

In [ ]:
df = df.sort_values(by="retail_banking", ascending=False)
df.iloc[0:5]

,credit_reporting,debt_collection,mortgages_and_loans,credit_card,retail_banking
account,0.416318,0.325808,0.163319,0.314431,0.590591
bank,0.024043,0.039606,0.103524,0.155371,0.340056
money,0.012966,0.036922,0.053483,0.060093,0.206533
would,0.050788,0.092880,0.195322,0.145342,0.138485
day,0.087358,0.065198,0.108384,0.095121,0.130474

## Pie graphs of top words

In [ ]:
df = df.sort_values(by="credit_reporting", ascending=False)
fig = px.pie(df, values=df.loc['credit'], names=column_names)
fig.update_layout(title = "'Credit': Top Term in Credit Reporting Compared to Other Classes")
fig.show()

In [ ]:
fig = px.pie(df, values=df.loc['debt'], names=column_names)
fig.update_layout(title = "'Debt': Top Term in Debt Collection Compared to Other Classes")
fig.show()

In [ ]:
fig = px.pie(df, values=df.loc['payment'], names=column_names)
fig.update_layout(title = "'Payment': Top Term in Mortgages and Loans compared to Other Classes")
fig.show()

In [ ]:
fig = px.pie(df, values=df.loc['card'], names=column_names)
fig.update_layout(title = "'Card': Top Term in Credit Card compared to Other Classes")
fig.show()

In [ ]:
fig = px.pie(df, values=df.loc['account'], names=column_names)
fig.update_layout(title = "'Account': Top Term in Retail Banking compared to Other Classes")
fig.show()

In [ ]:
df.head()

,credit_reporting,debt_collection,mortgages_and_loans,credit_card,retail_banking
credit,0.505595,0.372459,0.136271,0.370545,0.061344
account,0.416318,0.325808,0.163319,0.314431,0.590591
report,0.314272,0.188310,0.042440,0.052804,0.025841
information,0.241099,0.153487,0.076908,0.064074,0.065382
reporting,0.180959,0.095794,0.019932,0.016837,0.003814

In [ ]:
df.shape

(2009461, 5)

In [ ]:
df.tail()

,credit_reporting,debt_collection,mortgages_and_loans,credit_card,retail_banking
enforcement however,0.0,0.000016,0.000000,0.000000,0.000022
enforcement entity,0.0,0.000016,0.000000,0.000000,0.000022
firm upon,0.0,0.000000,0.000015,0.000000,0.000022
comparison ach,0.0,0.000000,0.000015,0.000000,0.000022
giving voucher,0.0,0.000000,0.000000,0.000094,0.000000

Export just the top 1500 rows for use in post-modeling EDA.

In [ ]:
df_export = df.iloc[:1500]

In [ ]:
df_export.shape

(1500, 5)

In [ ]:
df_export.to_csv('../project_data/corpus_lemm_tfidf.csv')